<?php $this->load->view('home/template/header');?>
<section class="page-section" id="what">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase ">What</h2>
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <div class="row" style="text-align:justify;">
            <div class="col-lg-12 text-justify">
                <p>Hello music lovers. You definitely want to hear good and interesting songs. Astro Music Share, is a
                    platform that will share links to selected songs chosen by Astro Music Share and share them randomly
                    with you.</p>

                <p>We use the YouTube platform to present these songs. We are looking for official YouTube links (but we
                    are looking for a few more from channels generated by YouTube), so you will get good sound quality,
                    as well as introducing all of the musicians to you.
                </p>

                <p>For now this platform is still a stub. So there are still many shortcomings in its operation. Every
                    link that we share is also shortened in a link shortener that contains advertisements.</p>

                <p>Thank you for reading the summary of what Astro Music Share is.</p>

            </div>
        </div>
    </div>
</section>
<section class="page-section" id="skip_ads">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">How To Skip Ads</h2>
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-justify">
                <p>Each link provided has been shortened to the url, which when clicked on the link will direct you to
                    an advertising page. After clicking to skip the ad, a new page is redirected to the music link.</p>
                <p>The following is a tutorial to skip the ad that will appear when you click on the link.</p>

                <p>
                    1.) Click the link from email that you received.
                    <img class="img img-fluid" src="<?=base_url('assets/img/skip_ads_01.png');?>" alt="skip_ads_01">
                </p>

                <p>
                    2.) Verify the captcha and klik the button (wait a few second, maybe something page will popup).
                    <img class="img img-fluid" src="<?=base_url('assets/img/skip_ads_02.png');?>" alt="skip_ads_02">
                </p>

                <p>
                    3.) Click the button (maybe something page will popup).
                    <img class="img img-fluid" src="<?=base_url('assets/img/skip_ads_03.png');?>" alt="skip_ads_03">
                </p>

            </div>
        </div>
    </div>
</section>
<?php $this->load->view('home/template/footer');?>